### PR TITLE
Fixes Android quick settings tile - issue #2646

### PR DESCRIPTION
**Pull request by nicolabeghin**
Fix for Android quick settings tile - based on new intents `com.tailscale.ipn.CONNECT_VPN` and `com.tailscale.ipn.DISCONNECT_VPN` from https://github.com/tailscale/tailscale/issues/3547

Screenshot_20231213_222936
Screenshot_20231213_222922

### CODE REVIEW

**Comment by nicolabeghin** [comment]
Any update on this? Thanks!

**Comment by nicolabeghin** [comment]
> This looks good to me. Just a few things: -Can you edit your commit message to also say "Fixes #2646" - this will fix the issuebot complaint. -Can you add a [DCO](https://wiki.linuxfoundation.org/dco#github)? Thanks!

done both - never used DCO before but should have added now, learning something new!

**Review by kari-ts — APPROVED** [review]
Thanks for the fix!

**Comment by bradfitz** [comment]
For cross-repo references you need to write:

```
Fixes tailscale/tailscale#2646
```

On its own line, conventionally.

Then it'll link & close to that other repo's issue.

**Pull request merged**
