### PR TITLE
Prevent connecting loops when using connect intent more than once

### PR DESCRIPTION
**Pull request by brettjenkins**
Added a check to check if the VPN is connected before triggering the connect behaviour.

Was introduced in https://github.com/tailscale/tailscale-android/pull/87

Fixes: https://github.com/tailscale/tailscale/issues/8013

### CODE REVIEW

**Comment by CrazyWolf13** [comment]
> Doing some more testing before I convert this into a full PR.

Huge thank you for creating this fix! 🔥❤️

**Comment by anoninthekop** [comment]
Hi, when will this fix be available on the playstore. Now whenever I start tailscale with tasker I have to manually force close the app to disconnect.

**Comment by plia7** [comment]
> Ready for review, @DentonGentry mind checking this over? Thanks :)

Hello, was this PR approved and pulled into the main release branch? It's been 2 months now, and we're eager for this fix.

Thank you.

**Comment by plia7** [comment]
> Hi, when will this fix be available on the playstore. Now whenever I start tailscale with tasker I have to manually force close the app to disconnect.

@anoninthekop I got it working without the fix, all you need to do is to send the disconnect intent twice, just give like a 5 seconds wait after each send intent... works like a charm.

**Comment by DentonGentry** [comment]
Tested locally.

**Review by DentonGentry — APPROVED** [review]

**Pull request merged**
