### PR TITLE
android/ui: add game of life to show progress when connecting (ENG-2860)

### PR DESCRIPTION
**Pull request by agottardo**
Fixes ENG-2860

Adds a game of life animation with the Tailscale logo when launching the app and waiting for the VPN tunnel to be established.

### CODE REVIEW

**Comment by oxtoacart** [comment]
Nice! While you're in here, could you use that for the LoadingIndicator.kt too? Something like this

```
fun Wrap(content: @Composable () -> Unit) {
    Box(
        modifier = Modifier.fillMaxWidth(),
        contentAlignment = Alignment.Center,
    ) {
      content()
      val isLoading = loading.collectAsState().value
      if (isLoading) {
        Box(Modifier.matchParentSize().background(Color.Gray.copy(alpha = 0.75f)))

        Column(
            modifier = Modifier.fillMaxWidth(),
            horizontalAlignment = Alignment.CenterHorizontally) {
              TailscaleLogoView(animated = true, Modifier.size(72.dp))
            }
      }
    }
  }
}
```

**Review by oxtoacart — APPROVED** [review]

**Comment by agottardo** [comment]
Merging this, will make the LoadingIndicator change in a separate PR.

**Review by barnstar — COMMENTED** [review]
Best feature everr.

**Comment by oxtoacart** [comment]
@agottardo I included the loading indicator change in [here](https://github.com/tailscale/tailscale-android/pull/243).

**Pull request merged**
