### PR TITLE
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find :ipn:.

### PR DESCRIPTION
**Pull request by xxzgithub**
error：1.Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
error：2.Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find :ipn:.

截屏2023-05-18 21 58 15
截屏2023-05-18 22 32 30

可以提供一下ipn@aar lib包嘛，谢谢！！！

### CODE REVIEW

**Review by DentonGentry — CHANGES_REQUESTED** [review]
I suspect you intended this to go to your own upstream.

**Comment by xxzgithub** [comment]
@DentonGentry I don't quite understand what you're saying. I'm in China and I made an error while compiling. Even if I broke the wall, I couldn't synchronize it inp@aar Please provide a solution or solution. Thank you

**Comment by DentonGentry** [comment]
This pull request suggests that we merge our own release branch back into main. This is clearly the wrong thing to do.

To build the Android app use `make tailscale-debug.apk`.

If you need support in something you are welcome to file an issue at https://github.com/tailscale/tailscale/issues
I'm going to close this pull request.

**Comment by xxzgithub** [comment]
好的，谢谢，请您关闭此问题

**Comment by xxzgithub** [comment]
Okay, thank you. Please close this issue

**Pull request closed without merging**
