### PR TITLE
go.mod: update to tailscale HEAD

### PR DESCRIPTION
**Pull request by danderson**
And update build logic to account for the API change in tailscale.com/version.

Signed-off-by: David Anderson <dave@natulte.net>

### CODE REVIEW

**Review by bradfitz — APPROVED** [review]

**Comment by DentonGentry** [comment]
The build failure is due to removal of the https://github.com/tailscale/go/releases/download/build-13373caf926b991ba7d7babe8b5bc79a325c3fad/linux.tar.gz toolchain and not related to this PR.

**Comment by bradfitz** [comment]
how do those toolchains get removed?

**Comment by DentonGentry** [comment]
> how do those toolchains get removed?

Ah: https://github.com/tailscale/go/releases/download/build-13373caf926b991ba7d7babe8b5bc79a325c3fad/linux.tar.gz is the new toolchain which this PR is pulling in.

Toolchain releases until about a week ago included a linux.tar.gz build artifact, which the Android Makefile expects. A side-effect of https://github.com/tailscale/corp/issues/9005 happened to remove linux.tar.gz, now the caller must choose linux-amd64.tar.gz or linux-arm64.tar.gz.

So I guess it is this PR after all.

**Comment by bradfitz** [comment]
Yeah, Dave cleaned up the tailscale/go GitHub Actions a bunch in https://github.com/tailscale/go/commit/954407f92b832496d861807de879680d307cbbff , https://github.com/tailscale/go/commit/d977a8ce6002f3a69470ae2111c3a128363b957c , https://github.com/tailscale/go/commit/26292c0a2e9823c4216e8776912a43fd9e50d444 and one side effect IIRC was that we were over-building/including stuff in our outputs. I guess we'd come to rely on that here. Yay Hyrum!

**Comment by danderson** [comment]
Choosing isn't required, linux.tar.gz was in fact just an amd64 build. For legacy reasons, it didn't include the architecture in its name. I fixed that as I was doing other maintenance, but didn't know that other repos rely on the same toolchain logic. I can fix that up.

**Comment by danderson** [comment]
Fixed the toolchain fetching bug in tailscale/tailscale, updated go.mod here again, and fixed a build breakage caused by an API change in tailscale/tailscale. `make tailscale-debug.apk` works again.

**Review by bradfitz — APPROVED** [review]

**Review by DentonGentry — APPROVED** [review]

**Pull request merged**
