### PR TITLE
cmd/tailscale: don't render ShareeNode peers

### PR DESCRIPTION
**Pull request by bradfitz**
Fixes tailscale/corp#11006

### CODE REVIEW

**Comment by bradfitz** [comment]
Untested.

**Review by DentonGentry — APPROVED** [review]

**Comment by bradfitz** [comment]
@DentonGentry, leaving for you to merge when happy, with or without testing :)

**Comment by gbraad** [comment]
please, this is needed. half on the nodes in my network show "device-of-shared-to-user" (ShareeNode=true)

**Comment by bradfitz** [comment]
@kari-ts, can you test and merge if good?

**Comment by gbraad** [comment]
I hoped the action would have an artifact for testing. I'll try to build this instead.

**Comment by kari-ts** [comment]
Tested and confirmed

**Pull request merged**
