### PR TITLE
UI/exit node status indicators (emphasizes the added functionality)

### PR DESCRIPTION
**Pull request by aalokkamble**
Refactored code exit node screen UI and improved visual feedback:

1. Improved clarity: Unavailable nodes are now displayed in gray for better indication of their status.
2. Enhanced user experience: The selected exit node, if offline, is now highlighted in red on the main screen for clear visual confirmation.

### CODE REVIEW

**Comment by aalokkamble** [comment]
@sonovawolf Please review.

I know this is not the place to discuss changes but here is my recommendation: 

current single file, ui.go, is getting cumbersome. Splitting it offers advantages:

Readability: Functions grouped by purpose make code easier to understand.
Maintainability: Changes become isolated, reducing unintended side effects.
Collaboration: Developers can work on different parts simultaneously.

Here's the plan:

Analyze: Identify logical boundaries in ui.go to split by features.
Structure: Define a clear file structure for related functionalities.
Docs: Update documentation/comments to reflect the new organization.

Splitting ui.go will create a cleaner, more manageable codebase for future development.

**Comment by kari-ts** [comment]
> @sonovawolf Please review.
> 
> I know this is not the place to discuss changes but here is my recommendation:
> 
> current single file, ui.go, is getting cumbersome. Splitting it offers advantages:
> 
> Readability: Functions grouped by purpose make code easier to understand. Maintainability: Changes become isolated, reducing unintended side effects. Collaboration: Developers can work on different parts simultaneously.
> 
> Here's the plan:
> 
> Analyze: Identify logical boundaries in ui.go to split by features. Structure: Define a clear file structure for related functionalities. Docs: Update documentation/comments to reflect the new organization.
> 
> Splitting ui.go will create a cleaner, more manageable codebase for future development.

Hey @aalokkamble, thank you so much for preparing these contributions! We've just started on a large set of changes that will replace the gioui code in this application with a Kotlin implemented GUI instead, which we expect will improve our maintenance costs and improve our ability to ensure that our app keeps up with the latest Android features. We do not yet have an organized way for contributors to follow that work stream, as it's still relatively early, getting the initial IPC and build system wiring in a good state. The existing gioui code base will be entering a bug-fix only phase as we move forward with this new strategy.

**Comment by agottardo** [comment]
Closing this PR since it targets the old Go codebase, and the feature has been implemented in recently shipped versions.

**Pull request closed without merging**
