### PR TITLE
Feature: machine status icon added.

### PR DESCRIPTION
**Pull request by aalokkamble**
added device status icon similar to iOS UI

markup_1000036970

### CODE REVIEW

**Comment by aalokkamble** [comment]
@sonovawolf @bradfitz  please review.

**Comment by kari-ts** [comment]
Thanks for working on this. A few issues:
-in a tailnet with more than one user "MY DEVICES" distinguishes between your devices and other users' devices. "MACHINES" is unclear. 
-the size of the dot looks great, but the alignment should be vertically centered to a lowercase letter, since machine names won't have uppercase letters

**Comment by aalokkamble** [comment]
@kari-ts Hi I have made the changes. Please review.

- Aligned dot vertically with lowercase letters for machine names.
- 'Machine' now reverted to 'My Devices'. (This was done to match our website UI)

**Comment by aalokkamble** [comment]
Screenshot for reference

**Comment by sonovawolf** [comment]
Hey @aalokkamble, thank you for the changes, now the alignment looks great.

Is it the screenshot or are the dots slightly horizontally squished and not entirely circular?

**Comment by sonovawolf** [comment]
Ah, I see. That's why it's not a full circle. That also has the added problem of changing the shape with the font… do you mind making it an actual circle? Either via svg or by creating a shape?

**Comment by aalokkamble** [comment]
Now using perfect circle 🙂

**Comment by sonovawolf** [comment]
Great, thank you!

**Review by kari-ts — APPROVED** [review]

**Review by sonovawolf — APPROVED** [review]

**Pull request merged**
