### PR TITLE
Implement taildrop for Android < 10

### PR DESCRIPTION
**Pull request by eliasnaur**

### CODE REVIEW

**Comment by DentonGentry** [comment]
I built an image with this to install on a Nexus 7 (2013) running Android 6, but I don't see a change in behavior. When Taildrop sends a file to the Nexus7 the other machine shows the transfer progressing and completing, but no file appears in any folder within the "Files" app and no notification appears on the Nexus 7.

What should I expect?

**Comment by eliasnaur** [comment]
> I built an image with this to install on a Nexus 7 (2013) running Android 6, but I don't see a change in behavior. When Taildrop sends a file to the Nexus7 the other machine shows the transfer progressing and completing, but no file appears in any folder within the "Files" app and no notification appears on the Nexus 7.
> 

I created an Android 6 emulator instance and tested taildrop from my Pixel. I did get a notification, but clicking on the notification brought up a "Downloads" file view with no files. The Google Photos app showed the shared file(s) just fine, however, and there is no visible "Downloads" or "Files" app on the emulator launcher so I suppose its downloads view just doesn't work. As another datapoint, I tried to download an image from the browser which resulted in the browser crashing.

You may experience another problem since you don't even get the notification. Can you look in the device logs for anything interesting?

**Comment by DentonGentry** [comment]
The first error was:
```
09-27 07:22:17.746 15527 16027 I com.tailscale.ipn: processWaitingFiles: insertMedia: java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=15527, uid=10083 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
```

I went into Settings -> Apps -> Tailscale -> Permissions, and saw that neither Phone not Storage was approved. I toggled them both on. No request or notification asking for those permissions had appeared, though I don't recall Android 6 asking for permissions. This may be related to sideloading instead of going through the Play Store?

Sending a file to the Nexus 7 still doesn't pop up a notification nor appear in the Files app, but now I get a different error (which is progress!):
```
09-27 07:24:42.604 15527 16026 I com.tailscale.ipn: processWaitingFiles: insertMedia: java.lang.IllegalArgumentException: no path was provided when inserting new file
```

**Comment by eliasnaur** [comment]
> The first error was:
> 
> ```
> 09-27 07:22:17.746 15527 16027 I com.tailscale.ipn: processWaitingFiles: insertMedia: java.lang.SecurityException: Permission Denial: writing com.android.providers.media.MediaProvider uri content://media/external/file from pid=15527, uid=10083 requires android.permission.WRITE_EXTERNAL_STORAGE, or grantUriPermission()
> ```
> 
> I went into Settings -> Apps -> Tailscale -> Permissions, and saw that neither Phone not Storage was approved. I toggled them both on. No request or notification asking for those permissions had appeared, though I don't recall Android 6 asking for permissions. This may be related to sideloading instead of going through the Play Store?
> 
> Sending a file to the Nexus 7 still doesn't pop up a notification nor appear in the Files app, but now I get a different error (which is progress!):
> 
> ```
> 09-27 07:24:42.604 15527 16026 I com.tailscale.ipn: processWaitingFiles: insertMedia: java.lang.IllegalArgumentException: no path was provided when inserting new file
> ```

Are you sure you're running Android 6 (api level 23)? These errors seem to come from code guarded by a version check on Android 10 (api level 29).

**Comment by DentonGentry** [comment]
It says Android 6.0.1 in About Tablet.

Screenshot_20210927-083614
.

**Comment by eliasnaur** [comment]
I double-checked, and the errors seem impossible for the < Android 10 branch in insertMedia. Can you try a patch similar to

```
diff --git android/src/main/java/com/tailscale/ipn/App.java android/src/main/java/com/tailscale/ipn/App.java
index 8e3081a..d66fccc 100644
--- android/src/main/java/com/tailscale/ipn/App.java
+++ android/src/main/java/com/tailscale/ipn/App.java
@@ -250,15 +250,17 @@ public class App extends Application {
        }

        String insertMedia(String name, String mimeType) throws IOException {
+               android.util.Log.i("com.tailscale.ipn", "Build.VERSION.SDK_INT: " + Build.VERSION.SDK_INT);
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
-                       ContentResolver resolver = getContentResolver();
+                       throw new RuntimeException("???");
+                       /*ContentResolver resolver = getContentResolver();
                        ContentValues contentValues = new ContentValues();
                        contentValues.put(MediaStore.MediaColumns.DISPLAY_NAME, name);
                        if (!"".equals(mimeType)) {
                                contentValues.put(MediaStore.MediaColumns.MIME_TYPE, mimeType);
                        }
                        Uri root = MediaStore.Files.getContentUri("external");
-                       return resolver.insert(root, contentValues).toString();
+                       return resolver.insert(root, contentValues).toString();*/
                } else {
                        File dir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
```

and let me know how it fares?

**Comment by DentonGentry** [comment]
This doesn't make a lot of sense, but after commenting out most of insertMedia and adding the `RuntimeException("???");`, I now just get a black screen when the app starts with a `fatal error: no surface created yet EGL_KHR_surfaceless_context is not supported` error.

I did `make clean` before building again and had reinstalled the release build in between, so a number of things had happened between the last test build and this one.

```
09-27 16:29:40.993   595  3056 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.tailscale.ipn/.IPNActivity bnds=[24,180][216,372] (has extras)} from uid 10014 on display 0
09-27 16:29:41.002   194   625 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: none)
09-27 16:29:41.002   194   625 D ACDB-LOADER: ACDB -> send_afe_cal
09-27 16:29:41.002   194   625 D audio_hw_primary: enable_snd_device: snd_device(2: speaker)
09-27 16:29:41.010   194   625 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback
09-27 16:29:41.029   595  2062 I ActivityManager: Start proc 9772:com.tailscale.ipn/u0a84 for activity com.tailscale.ipn/.IPNActivity
09-27 16:29:41.030  9772  9772 I art     : Late-enabling -Xcheck:jni
09-27 16:29:41.132  9772  9772 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.tailscale.ipn.QuickToggleService>
09-27 16:29:41.132  9772  9772 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.tailscale.ipn.QuickToggleService>
09-27 16:29:41.133  9772  9772 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.tailscale.ipn.QuickToggleService>
09-27 16:29:41.312  9772  9795 I EngineFactory: Provider GmsCore_OpenSSL not available
09-27 16:29:41.326  9772  9797 I com.tailscale.ipn: logtail started
09-27 16:29:41.327  9772  9797 I com.tailscale.ipn: goSetupLogs: success
09-27 16:29:41.340  6837  6837 W Binder_5: type=1400 audit(0.0:1011): avc: denied { ioctl } for path="socket:[55441]" dev="sockfs" ino=55441 ioctlcmd=7704 scontext=u:r:surfaceflinger:s0 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
09-27 16:29:41.340  6837  6837 W Binder_5: type=1400 audit(0.0:1012): avc: denied { ioctl } for path="socket:[55441]" dev="sockfs" ino=55441 ioctlcmd=7704 scontext=u:r:surfaceflinger:s0 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
09-27 16:29:41.351  9772  9805 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
09-27 16:29:41.340  6837  6837 W Binder_5: type=1400 audit(0.0:1013): avc: denied { ioctl } for path="socket:[55444]" dev="sockfs" ino=55444 ioctlcmd=7704 scontext=u:r:surfaceflinger:s0 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
09-27 16:29:41.340  6837  6837 W Binder_5: type=1400 audit(0.0:1014): avc: denied { ioctl } for path="socket:[55444]" dev="sockfs" ino=55444 ioctlcmd=7704 scontext=u:r:surfaceflinger:s0 tcontext=u:r:surfaceflinger:s0 tclass=unix_stream_socket permissive=0
09-27 16:29:41.353  9772  9800 I com.tailscale.ipn: 4.3M/49.0M dns: using *router.CallbackRouter
09-27 16:29:41.354  9772  9800 I com.tailscale.ipn: 4.4M/49.0M link state: interfaces.State{defaultRoute=wlan0 ifs={wlan0:[10.1.10.144/24 2602:248:7b4a:ff60:a046:d5f3:5c11:98dd/64 2602:248:7b4a:ff60:ae22:bff:fe49:ba4e/64]} v4=true v6=true}
09-27 16:29:41.366  9772  9800 I com.tailscale.ipn: 4.4M/49.2M magicsock: disco key = d:525aa95ebf80693b
09-27 16:29:41.366  9772  9800 I com.tailscale.ipn: 4.4M/49.2M Creating wireguard device...
09-27 16:29:41.368  9772  9800 I com.tailscale.ipn: 4.5M/49.4M Bringing wireguard device up...
09-27 16:29:41.370  9772  9799 I com.tailscale.ipn: 4.5M/49.4M Bringing router up...
09-27 16:29:41.370  9772  9799 I com.tailscale.ipn: 4.5M/49.4M Clearing router settings...
09-27 16:29:41.371  9772  9800 I com.tailscale.ipn: 4.5M/49.4M Starting link monitor...
09-27 16:29:41.371  9772  9800 I com.tailscale.ipn: 4.5M/49.4M Engine created.
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1015): avc: denied { search } for name="1" dev="proc" ino=7248 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:init:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1016): avc: denied { search } for name="2" dev="proc" ino=2032 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1017): avc: denied { search } for name="3" dev="proc" ino=2033 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1018): avc: denied { search } for name="6" dev="proc" ino=2036 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1019): avc: denied { search } for name="16" dev="proc" ino=2037 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1020): avc: denied { search } for name="17" dev="proc" ino=2038 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1021): avc: denied { search } for name="18" dev="proc" ino=2039 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1022): avc: denied { search } for name="19" dev="proc" ino=2040 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1023): avc: denied { search } for name="23" dev="proc" ino=2041 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1024): avc: denied { search } for name="24" dev="proc" ino=2042 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1025): avc: denied { search } for name="25" dev="proc" ino=2043 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1026): avc: denied { search } for name="26" dev="proc" ino=2044 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1027): avc: denied { search } for name="27" dev="proc" ino=2045 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1028): avc: denied { search } for name="28" dev="proc" ino=2046 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1029): avc: denied { search } for name="29" dev="proc" ino=2047 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.400  9772  9800 I com.tailscale.ipn: 4.8M/49.7M netmap packet filter: (not ready yet)
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1030): avc: denied { search } for name="30" dev="proc" ino=2048 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1031): avc: denied { search } for name="31" dev="proc" ino=10241 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1032): avc: denied { search } for name="32" dev="proc" ino=10242 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1033): avc: denied { search } for name="33" dev="proc" ino=10243 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381   735   735 W Binder_4: type=1400 audit(0.0:1034): avc: denied { ioctl } for path="socket:[49068]" dev="sockfs" ino=49068 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
09-27 16:29:41.402  9772  9795 I com.tailscale.ipn: 4.8M/50.0M Start
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1035): avc: denied { search } for name="34" dev="proc" ino=10244 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.402  9772  9795 I com.tailscale.ipn: 4.8M/50.0M using backend prefs
09-27 16:29:41.381   735   735 W Binder_4: type=1400 audit(0.0:1036): avc: denied { ioctl } for path="socket:[49068]" dev="sockfs" ino=49068 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1037): avc: denied { search } for name="35" dev="proc" ino=10245 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1038): avc: denied { search } for name="36" dev="proc" ino=10246 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1039): avc: denied { search } for name="37" dev="proc" ino=10247 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1040): avc: denied { search } for name="38" dev="proc" ino=10248 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1041): avc: denied { search } for name="39" dev="proc" ino=10249 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.410  9772  9805 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
09-27 16:29:41.418  9772  9805 I OpenGLRenderer: Initialized EGL, version 1.4
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1042): avc: denied { search } for name="40" dev="proc" ino=10250 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1043): avc: denied { search } for name="41" dev="proc" ino=10251 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.381  9800  9800 W m.tailscale.ipn: type=1400 audit(0.0:1044): avc: denied { search } for name="42" dev="proc" ino=10252 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:kernel:s0 tclass=dir permissive=0
09-27 16:29:41.433  9772  9795 I com.tailscale.ipn: 5.1M/52.3M backend prefs for "ipn-android": Prefs{ra=true dns=true want=false host="Nexus 7" Persist=nil}
09-27 16:29:41.434  9772  9797 I com.tailscale.ipn: 5.1M/52.3M netmap packet filter: (not ready yet)
09-27 16:29:41.435  9772  9795 I com.tailscale.ipn: 5.1M/52.5M got initial portlist info in 1ms
09-27 16:29:41.437  9772  9795 I com.tailscale.ipn: 5.1M/52.7M control: HostInfo: {"IPNVersion":"date.20210907","BackendLogID":"31047a00483d8f4afb86749caba9543e9fe148076d7b2dfcc1122b2edc42491f","OS":"android","OSVersion":"6.0.1","DeviceModel":"asus Nexus 7","Hostname":"Nexus 7","GoArch":"arm"}
09-27 16:29:41.437  9772  9795 I com.tailscale.ipn: 5.1M/52.7M Backend: logs: be:31047a00483d8f4afb86749caba9543e9fe148076d7b2dfcc1122b2edc42491f fe:
09-27 16:29:41.438  9772  9799 I com.tailscale.ipn: 5.1M/52.7M control: authRoutine: state:new; goal=nil paused=false
09-27 16:29:41.439  9772  9799 I com.tailscale.ipn: 5.1M/52.8M control: mapRoutine: state:new
09-27 16:29:41.440  9772  9799 I com.tailscale.ipn: 5.1M/52.8M Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
09-27 16:29:41.440  9772  9799 I com.tailscale.ipn: 5.1M/52.8M blockEngineUpdates(true)
09-27 16:29:41.441  9772  9793 I com.tailscale.ipn: 5.1M/52.8M wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
09-27 16:29:41.442  9772  9793 I com.tailscale.ipn: 5.2M/53.1M wgengine: Reconfig: configuring router
09-27 16:29:41.442  9772  9793 I com.tailscale.ipn: 5.1M/52.8M health("overall"): error: state=NeedsLogin, wantRunning=false
09-27 16:29:41.449  9772  9799 I com.tailscale.ipn: 5.3M/54.0M wgengine: Reconfig: configuring DNS
09-27 16:29:41.450  9772  9799 I com.tailscale.ipn: 4.5M/54.0M dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
09-27 16:29:41.450  9772  9799 I com.tailscale.ipn: 4.5M/54.0M dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
09-27 16:29:41.452  9772  9799 I com.tailscale.ipn: 4.2M/54.0M dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
09-27 16:29:41.468  9772  9800 I com.tailscale.ipn: fatal error: no surface created yet EGL_KHR_surfaceless_context is not supported
09-27 16:29:41.484  9772  9793 I com.tailscale.ipn: 4.2M/56.3M SetPrefs: Prefs{ra=true dns=true want=false host="Nexus 7" Persist=nil}
09-27 16:29:41.484  9772  9793 I com.tailscale.ipn: 4.2M/56.3M authReconfig: blocked, skipping.
09-27 16:29:41.500   595   613 I ActivityManager: Displayed com.tailscale.ipn/.IPNActivity: +483ms
09-27 16:29:41.503   966   966 I GoogleInputMethodServic: GoogleInputMethodService.onFinishInput():3446
09-27 16:29:41.503   966   966 I GoogleInputMethodServic: GoogleInputMethodService.onStartInput():2028
09-27 16:29:41.503   966   966 I DeviceUnlockedTag: DeviceUnlockedTag.notifyDeviceLockStatusChanged():38 Notify device unlocked.
09-27 16:29:42.794   595   649 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 100] to 56
09-27 16:29:44.255   194   625 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
09-27 16:29:44.255   194   625 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
```

**Comment by eliasnaur** [comment]
> This doesn't make a lot of sense, but after commenting out the code in insertMedia and adding the RuntimeException("???");, I now just get a black screen when the app starts with a `fatal error: no surface created yet EGL_KHR_surfaceless_context is not supported` error.
> 

I pushed a Gio update that should fix this issue (along with other graphics glitches on other low-spec devices).

Speaking of weird issues, I get

```
find: ‘/home/elias/.cache/tailscale-android-go-edbc3e19a064177abc6efe937cb84c2a261053ab’: No such file or directory
find: ‘/home/elias/.cache/tailscale-android-go-edbc3e19a064177abc6efe937cb84c2a261053ab’: No such file or directory
want: 91032a6740c8f28e0b1fd614b9dfc888b24cfbb1
got: 5cd337198ead0768975610a135e26257153198c7
rm -rf /home/elias/.cache/tailscale-android-go-*
wget https://github.com/tailscale/go/releases/download/build-edbc3e19a064177abc6efe937cb84c2a261053ab/linux.tar.gz -O "/tmp/tmp.of01Pla36c.tgz"
--2021-09-28 08:53:01--  https://github.com/tailscale/go/releases/download/build-edbc3e19a064177abc6efe937cb84c2a261053ab/linux.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-28 08:53:02 ERROR 404: Not Found.

make: *** [Makefile:46: toolchain] Error 8
```
if I don't comment out the `toolchain` rule from Makefile.

**Comment by DentonGentry** [comment]
I updated from your most recent changes, and the app renders without trouble now. The Gio update is good.

At startup it asked for permission to access photos, media, and files.
When I send a file to it, the notification appears and the file is in the Downloads folder.

Clearly I built or was running the wrong thing earlier, when adb showed errors in `insertMedia:`. I have no idea what, though.

Screenshot_20210928-002021

--------

Regarding the toolchain in the Makefile: I started using Tailscale's fork of the Go toolchain to fix https://github.com/tailscale/tailscale/issues/2478, which was an issue with upstream Go 1.16 and Tailscale's toolchain pulled in the fix early.

I updated the Makefile in `main` with current versions of the toolchain, however with Go 1.17 now out I may remove it altogether.

**Review by DentonGentry — APPROVED** [review]

**Pull request merged**
